- name: Install prereqs for skydive on controller
  hosts: controllers
  become: yes
  become_method: sudo
  tasks:
    - name: Install Opendk
      yum:
        name: java-openjdk
        state: present
    - name: Install Elasticsearch
      yum:
        name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.2.rpm
        state: present
    - name: Enable Easticsearch
      service:
        name: elasticsearch
        enabled: yes
        state: started

- name: Install skydive common repositories to all
  hosts: controllers,computes
  become: yes
  become_method: sudo
  tasks:
    - name: yum repos required for skydive
      yum:
        name: centos-release-virt-common,centos-release-qemu-ev,centos-release-openstack-newton,centos-release-opstools
        state: present
    - name: install common skydive packages
      yum:
        name: skydive,skydive-agent
        state: present

- name: install skydive.yaml configuration file
  hosts: controllers,computes
  become: yes
  become_method: sudo
  vars:
    auth_url: http://10.0.0.13:5000/v2.0
    admin_username: admin
    admin_password: hYgKP6tpxk7e4Ta6qGwedEVgP
    controller_ip: overcloud-controller-0.internalapi
    compute_ip: overcloud-novacompute-0.internalapi
  tasks:
    - name: copy skydive.yaml.j2
      copy: src=templates/skydive.yaml.j2 dest=/etc/skydive/skydive.yaml owner=root mode=600
    - name: Enable skydive-agent service
      service:
        name: skydive-agent
        enabled: yes
        state: started

- name: Install Skydive Analyzer
  hosts: controllers
  become: yes
  become_method: sudo
  tasks:
    - name: Install skydive-analyzer
      yum:
        name: skydive-analyzer
        state: present
    - name: Enable skydive-analyzer service
      service:
        name: skydive-analyzer
        enabled: yes
        state: started




