- name: populate variables for openstack rc
  hosts: localhost
  tasks:
    - name: grab username from overcloudrc
      shell: >
        cat {{ ansible_env.HOME }}/overcloudrc | grep export | awk '{print $2}' | grep OS_USERNAME | cut -d = -f 2
      register: username
    - name: grab password from overcloudrc
      shell: >
        cat {{ ansible_env.HOME }}/overcloudrc | grep export | awk '{print $2}' | grep -i OS_PASSWORD | cut -d = -f 2
      register: password
    - name: grab auth_url from overcloudrc
      shell: >
        cat {{ ansible_env.HOME }}/overcloudrc | grep export | awk '{print $2}' | grep -i OS_AUTH_URL | cut -d = -f 2
      register: auth_url
    - name: grab project name from overcloudrc
      shell: >
        cat {{ ansible_env.HOME }}/overcloudrc | grep export | awk '{print $2}' | grep -i OS_PROJECT_NAME | cut -d = -f 2
      register: project_name
    - name: debug vars
      debug: msg="user={{ username.stdout }}, password={{ password.stdout }}, auth_url={{ auth_url.stdout }}, project_name={{ project_name.stdout }}" 

- name: Install prereqs for skydive on controller
  hosts: controllers 
  become: yes
  become_method: sudo
  tasks:
    - name: Install Opendk
      yum:
        name: java-openjdk
        state: present
    - name: Install Elasticsearch
      yum:
        name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.2.rpm
        state: present
    - name: Enable Easticsearch
      service:
        name: elasticsearch
        enabled: yes
        state: started

- name: Install skydive common repositories to all
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: yum repos required for skydive
      yum:
        name: centos-release-virt-common,centos-release-qemu-ev,centos-release-openstack-newton,centos-release-opstools
        state: present
    - name: install common skydive packages
      yum:
        name: skydive,skydive-agent
        state: present

- name: install skydive.yaml configuration file
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: copy skydive.yaml.j2
      template: src=templates/skydive.yaml.j2 dest=/etc/skydive/skydive.yml owner=root mode=600
    - name: Enable skydive-agent service
      service:
        name: skydive-agent
        enabled: yes
        state: started

- name: Install Skydive Analyzer
  hosts: controllers
  become: yes
  become_method: sudo
  tasks:
    - name: Install skydive-analyzer
      yum:
        name: skydive-analyzer
        state: present
    - name: Enable skydive-analyzer service
      service:
        name: skydive-analyzer
        enabled: yes
        state: started
    - name: add a iptables input
      become: yes
      iptables:
        action: insert
        chain: INPUT
        protocol: tcp
        destination_port: 8082
        jump: ACCEPT
